# -  /𝐶𝑌𝛣𝛯𝑅 亇𝐻び𝑆𝐻𝜟𝚴 𝛩𝐹𝐹𝐼𝐶𝐼𝜟𝐿/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/cybre-citty/King-x /root/cybre-citty
WORKDIR /root/cybre-citty/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /𝐶𝑌𝛣𝛯𝑅 𝑌𝜟𝜥び𝛧𝜟 亇𝛯𝜟𝛭/
